### STAGE 1: Build ###
FROM node:16.5

RUN apt-get update && \
    apt-get install -yq  libnss3 libatk-bridge2.0-0 libx11-xcb1 libxcb-dri3-0 libdrm2 libgbm1 libasound2 libgtk-3-0 && \
    apt-get clean && apt-get autoremove -y && rm -rf /var/lib/apt/lists/*

WORKDIR /code

COPY package.json package-lock.json /code/

RUN npm config set depth 0 && npm cache clean --force && npm install -q --no-progress && npm rebuild

COPY . .

CMD [ "npm", "run", "test" ]
