version: '3.5'

services:
  olmarket:
    image: registry.ortolang.fr/ortolang/ortolang-market:${VERSION}
    environment: 
      - 'api_url=${API_URL}'
      - 'prerender_server_ip=prerender'
      - 'prerender_server_port=3000'
    deploy:
      labels:
        traefik.http.routers.ortolang-market.rule: "Host(`${FRONTEND_HOST}`) && PathPrefix(`/market`,`/assets`,`/producers`,`/contributors`,`/workspaces`,`/profiles`,`/seo`)"
        traefik.http.services.ortolang-market-service.loadbalancer.server.port: "80"
        traefik.http.routers.ortolang-market.tls: "true"
    networks:
      - proxy
      - ortolang-network

networks:
  ortolang-network:
    external: true
    name: ${ORTOLANG_NETWORK}
  proxy:
    external: true